apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-fe
  namespace: argocd
  labels:
    app: sample-app-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-fe
  template:
    metadata:
      labels:
        app: sample-app-fe
    spec:
      containers:
      - name: sample-app-fe
        image: docker.io/ackresponse/sample_app_fe:latest
        ports:
        - containerPort: 3000
        env:
        - name: Backend-URL
          value: "http://34.142.97.85/api/backend-call"
