apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample_app_fe
  namespace: argocd
  labels:
    app: sample_app_fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample_app_fe
  template:
    metadata:
      labels:
        app: sample_app_fe
    spec:
      containers:
      - name: sample_app_fe
        image: docker.io/ackresponse/sample_app_fe:latest
        ports:
        - containerPort: 3000
