name: Push Docker Image

on:
  push:
    branches:
      - trivy-test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ackresponse
          password: ${{ secrets.DCKR_PSWD }}

      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v2'
      #   with:
      #     version: '>= 363.0.0'
      #     install_components: "gke-gcloud-auth-plugin"

      # -
      #   name: Connect with google console
      #   uses: "google-github-actions/auth@v2"
      #   with:
      #     project_id: "concepts-demo"
      #     credentials_json: ${{ secrets.NG_SA_KEY_GCLOUD }}

      # - uses: google-github-actions/get-gke-credentials@v1
      #   with:
      #     cluster_name: argocd-3
      #     location: europe-west3
      #     project_id: concepts-demo

      # - name: Fetch Backend IP
      #   id: fetch-backend-ip
      #   run: |
      #     BACKEND_IP=$(kubectl get service sample-app-be-service -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
      #     echo "Backend IP: $BACKEND_IP"
      #     echo "BACKEND_IP=$BACKEND_IP" >> $GITHUB_ENV

      # - name: Update Backend URL in Axios Code
      #   run: |
      #     sed -i "s|http://<backend-loadbalancer-ip>|http://$BACKEND_IP|g" service/backend-call.ts

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ackresponse/sample-app-fe:1.9 # build the same tag you want to scan
          load: true
          push: false # only build locally

      - name: List Docker Images
        run: docker images | grep ackresponse/sample-app-fe || true

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "ackresponse/sample-app-fe:1.9" # scan the locally built image
          format: "table"
          severity: "LOW"
          exit-code: "0" # fail pipeline if HIGH or CRITICAL vulnerabilities are found

      - name: Push Docker Image
        # if: success() # only push if Trivy scan passed
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ackresponse/sample-app-fe:1.9
          push: true
