name: Push Docker Image

on:
  push:
    branches:
      - trivy-test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ackresponse
          password: ${{ secrets.DCKR_PSWD }}

      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v2'
      #   with:
      #     version: '>= 363.0.0'
      #     install_components: "gke-gcloud-auth-plugin"

      # -
      #   name: Connect with google console
      #   uses: "google-github-actions/auth@v2"
      #   with:
      #     project_id: "concepts-demo"
      #     credentials_json: ${{ secrets.NG_SA_KEY_GCLOUD }}

      # - uses: google-github-actions/get-gke-credentials@v1
      #   with:
      #     cluster_name: argocd-3
      #     location: europe-west3
      #     project_id: concepts-demo

      # - name: Fetch Backend IP
      #   id: fetch-backend-ip
      #   run: |
      #     BACKEND_IP=$(kubectl get service sample-app-be-service -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
      #     echo "Backend IP: $BACKEND_IP"
      #     echo "BACKEND_IP=$BACKEND_IP" >> $GITHUB_ENV

      # - name: Update Backend URL in Axios Code
      #   run: |
      #     sed -i "s|http://<backend-loadbalancer-ip>|http://$BACKEND_IP|g" service/backend-call.ts

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ackresponse/sample-app-fe:1.9 # build the same tag you want to scan
          load: true
          push: false # only build locally

      - name: List Docker Images
        run: docker images | grep ackresponse/sample-app-fe || true

      - name: Run Trivy Scan
        id: trivy
        uses: aquasecurity/trivy-action@0.20.0
        continue-on-error: true
        with:
          image-ref: "ackresponse/sample-app-fe:1.9" # scan the locally built image
          format: "json"
          severity: "HIGH,CRITICAL"
          output: trivy-result.json
          exit-code: "1" # fail pipeline if HIGH or CRITICAL vulnerabilities are found

      # Check Scan Results
      - name: Check Trivy Scan Results
        id: check-scan
        run: |
          if [ "${{ steps.trivy.outcome }}" == "failure" ]; then
            echo "scan_status=failure" >> $GITHUB_ENV
          else
            echo "scan_status=success" >> $GITHUB_ENV
          fi

      - name: Generate Markdown report
        if: env.scan_status == "failure" # only generate report if Trivy scan failed
        id: trivy-md
        run: |
          echo "### vulnerability Summary" > trivy-report.md
          echo "" >> trivy-report.md

          CRIT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' trivy-result.json)
          HIGH=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH")] | length' trivy-result.json)
          echo "- CRITICAL: $CRIT" >> trivy-report.md
          echo "- HIGH: $HIGH" >> trivy-report.md
          echo "" >> trivy-report.md

          echo "| Severity | Package | Version | CVE | Link |" >> trivy-report.md
          echo "|---|---|---|---|---|" >> trivy-report.md
          jq -r '
            .Results[]?.Vulnerabilities[]? |
            "| \(.Severity) | \(.PkgName) | \(.InstalledVersion) | \(.VulnerabilityID) | \(.PrimaryURL) |"
          ' trivy-result.json >> trivy-report.md

      - name: Await for manual approval
        if: env.scan_status == "failure" # only create issue if Trivy scan failed
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{github.TOKEN }}
          title: "Trivy Scan Results"
          summary: "Vulnerabilities found in the scan. Please review before proceeding."
          issue-title: "Manual Approval Required: Trivy Scan Results"
          issue-body: |
            Trivy scan results for the Docker image `ackresponse/sample-app-fe:1.9`:
            $(cat trivy-report.md)
            👉 Full JSON report is available in workflow logs.
          labels: "trivy, scan, manual-approval"
          minimum-approvals: 1
          approvers: ackresponse-ar,GurungDev # GitHub username of the approver

      - name: Push Docker Image
        if: env.scan_status == "success" || ( env.scan_status == "failure" && success() )
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ackresponse/sample-app-fe:1.9
          push: true
