name: Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ackresponse
          password: ${{ secrets.DCKR_PSWD }}

      - name: Fetch Backend IP
        id: fetch-backend-ip
        run: |
          BACKEND_IP=$(kubectl get service sample-app-be-service -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Backend IP: $BACKEND_IP"
          echo "BACKEND_IP=$BACKEND_IP" >> $GITHUB_ENV

      - name: Update Backend URL in Axios Code
        run: |
          sed -i "s|http://<backend-loadbalancer-ip>|http://$BACKEND_IP|g" service/backend-call.ts
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ackresponse/sample-app-fe:1.2
