name: Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ackresponse
          password: ${{ secrets.DCKR_PSWD }}


      - 
        name: Connect with google console
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "concepts-demo"
          credentials_json: ${{ secrets.NG_SA_KEY_GCLOUD }}

      - name: Configure Kubernetes Cluster
        run: |
          gcloud container clusters get-credentials argocd-3 --region europe-west3 --project concepts-demo

      - name: Add Google Cloud SDK Repository
        run: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update
        
  
      - name: Install gke-gcloud-auth-plugin
        run: |
            sudo apt-get update
            sudo apt-get install -y gke-gcloud-auth-plugin
        env:
            CLOUDSDK_CORE_DISABLE_PROMPTS: '1'

      - name: Fetch Backend IP
        id: fetch-backend-ip
        run: |
          BACKEND_IP=$(kubectl get service sample-app-be-service -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Backend IP: $BACKEND_IP"
          echo "BACKEND_IP=$BACKEND_IP" >> $GITHUB_ENV

      - name: Update Backend URL in Axios Code
        run: |
          sed -i "s|http://<backend-loadbalancer-ip>|http://$BACKEND_IP|g" service/backend-call.ts
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ackresponse/sample-app-fe:1.2
